/* SPDX-License-Identifier: 0BSD */
#include "db.h"
#include <stdio.h>
#include <string.h>
#include <strings.h>
#include <stdlib.h>

const char *db_tv_name(ctr_region r)
{
	switch (r) {
	case REGION_PAL:   return "PAL";
	case REGION_DENDY: return "DENDY";
	default:           return "NTSC";
	}
}

static ctr_region tv_parse(const char *s)
{
	if (!strcasecmp(s, "PAL"))   return REGION_PAL;
	if (!strcasecmp(s, "DENDY")) return REGION_DENDY;
	return REGION_NTSC;
}

/* Mapper numbers mean nothing on a card face; the chip name means something to
 * anyone who would install this. */
const char *db_mapper_name(int mapper)
{
	switch (mapper) {
	case 0:  return "NROM";
	case 2:  return "UNROM";
	case 23: return "VRC2";
	case 1:  return "MMC1";
	case 4:  return "MMC3";
	default: return "MAPPER";
	}
}

/* Splits on '|' in place; returns field count. Trailing fields may be absent. */
static int split(char *line, char *f[], int maxf)
{
	int n = 0;
	f[n++] = line;
	while (n < maxf) {
		char *p = strchr(f[n-1], '|');
		if (!p) break;
		*p = 0;
		f[n++] = p + 1;
	}
	return n;
}

static void trim(char *s)
{
	size_t n = strlen(s);
	while (n && (s[n-1]=='\n' || s[n-1]=='\r' || s[n-1]==' ' || s[n-1]=='\t')) s[--n] = 0;
}

bool db_load(const char *path, contra_db *out)
{
	FILE *f = fopen(path, "r");
	char line[512];

	memset(out, 0, sizeof(*out));
	if (!f) return false;

	while (fgets(line, sizeof(line), f) && out->count < DB_MAX) {
		char *fld[8];
		int n;
		db_entry *e;

		trim(line);
		if (line[0] == '#' || line[0] == 0) continue;
		n = split(line, fld, 8);
		if (n < 2 || strlen(fld[0]) != 40) continue;

		e = &out->e[out->count++];
		memset(e, 0, sizeof(*e));
		snprintf(e->sha1,  sizeof(e->sha1),  "%s", fld[0]);
		snprintf(e->title, sizeof(e->title), "%s", fld[1]);
		if (n > 2) snprintf(e->region, sizeof(e->region), "%s", fld[2]);
		e->tv     = (n > 3) ? tv_parse(fld[3]) : REGION_NTSC;
		e->mapper = (n > 4) ? atoi(fld[4]) : -1;
		e->crt    = (n > 5) ? (atoi(fld[5]) != 0) : true;
		e->crop   = (n > 6) ? (atoi(fld[6]) != 0) : false;
		if (n > 7) snprintf(e->note, sizeof(e->note), "%s", fld[7]);
	}
	fclose(f);
	return true;
}

bool db_save(const char *path, const contra_db *db)
{
	FILE *f = fopen(path, "w");
	int i;

	if (!f) return false;
	fprintf(f, "# Contrarian known-ROM database.\n"
	           "# payload-sha1 | title | region | tv | mapper | crt | crop | note\n"
	           "# payload-sha1 is SHA-1 of the ROM with its iNES header stripped.\n");
	for (i = 0; i < db->count; i++) {
		const db_entry *e = &db->e[i];
		fprintf(f, "%s|%s|%s|%s|%d|%d|%d|%s\n", e->sha1, e->title, e->region,
		        db_tv_name(e->tv), e->mapper, e->crt, e->crop, e->note);
	}
	fclose(f);
	return true;
}

db_entry *db_find(contra_db *db, const char *sha1hex)
{
	int i;
	for (i = 0; i < db->count; i++)
		if (!strcasecmp(db->e[i].sha1, sha1hex)) return &db->e[i];
	return NULL;
}

/* contra.fp -- text so it stays diffable in the repo:
 *   base <sha1> <count> <name...>
 *   <16 hex chars per block, whitespace separated>                      */
bool db_load_bases(const char *path, contra_bases *out)
{
	FILE *f = fopen(path, "r");
	char line[512];
	db_base *cur = NULL;

	memset(out, 0, sizeof(*out));
	if (!f) return false;

	while (fgets(line, sizeof(line), f)) {
		trim(line);
		if (line[0] == '#' || line[0] == 0) continue;

		if (!strncmp(line, "base ", 5)) {
			char sha[41], name[DB_STR];
			int cnt = 0;
			if (out->count >= DB_MAX_BASE) break;
			name[0] = 0;
			if (sscanf(line + 5, "%40s %d %95[^\n]", sha, &cnt, name) < 2) continue;
			cur = &out->b[out->count++];
			memset(cur, 0, sizeof(*cur));
			snprintf(cur->sha1, sizeof(cur->sha1), "%s", sha);
			snprintf(cur->name, sizeof(cur->name), "%s", name);
			cur->fp.total = cnt;
		} else if (cur) {
			const char *p = line;
			while (*p) {
				char *end;
				unsigned long long v;
				while (*p == ' ' || *p == '\t') p++;
				if (!*p) break;
				v = strtoull(p, &end, 16);
				if (end == p) break;
				if (cur->fp.count < NES_MAX_BLOCKS)
					cur->fp.blocks[cur->fp.count++] = (uint64_t)v;
				p = end;
			}
		}
	}
	fclose(f);
	return out->count > 0;
}

bool db_save_bases(const char *path, const contra_bases *b)
{
	FILE *f = fopen(path, "w");
	int i, j;

	if (!f) return false;
	fprintf(f, "# Contrarian base fingerprints. Generated by tools/mkfp.\n"
	           "# Truncated one-way digests of 1K PRG blocks -- no ROM content.\n"
	           "# Lets an unknown ROM be scored even when no base ROM is on the card.\n");
	for (i = 0; i < b->count; i++) {
		fprintf(f, "base %s %d %s\n", b->b[i].sha1, b->b[i].fp.total, b->b[i].name);
		for (j = 0; j < b->b[i].fp.count; j++)
			fprintf(f, "%016llx%s", (unsigned long long)b->b[i].fp.blocks[j],
			        (j % 8 == 7 || j == b->b[i].fp.count - 1) ? "\n" : " ");
	}
	fclose(f);
	return true;
}
